require_relative 'ar.rb'

# Create three new products using the three different ways to create new AR objects.
# Ensure that all three new products are persisted to the database, without validations errors.

# Method 1: object space + set product object attributes + save
shampoo = Product.new

shampoo.id = (Product.last.id + 1)
shampoo.name = "Shampoo"
shampoo.description = "bubble"
shampoo.price = 10
shampoo.stock_quantity = 5
shampoo.category_id = 1
shampoo.created_at = Time.now
shampoo.updated_at = Time.now

shampoo.save
puts
puts "Inspect #{shampoo.name}:"
puts shampoo.inspect
puts


# Method 2: object space + hash argument + save
potato = Product.new( name:         "Potato",
                      description:  "spud",
                      price:          1,
                      stock_quantity: 400,
                      category_id:    5 )

potato.save
puts "Inspect #{potato.name}:"
puts potato.inspect
puts


# Method 3: create
munster = Product.create( name:         "Munster",
                          description:  "delish",
                          price:          7,
                          stock_quantity: 6,
                          category_id:    4 )

puts "Inspect #{munster.name}:"
puts munster.inspect
puts

# Create a Product object that is missing some required columns.
parm = Product.new(name: "Parmigiano Reggiano")
parm.save

puts "Inspect #{parm.name}:"
puts parm.inspect
puts

# Attempt to save this product and print all the AR errors which are generated.
puts "Errors generated by the attempted creation of #{parm.name}:"
Product.new(name: "Parmigiano Reggiano").errors.messages.each do |column, errors|
  errors.each do |error|
    puts "The #{column} property #{error}."
  end
end
puts

